const std = @import("std");
const ctime = @cImport({
    @cInclude("time.h");
});

// NOTE: The `dependencies` field can't be represented https://github.com/ziglang/zig/issues/22775
//       Once this merged PR https://github.com/ziglang/zig/pull/22907 has made it into a release
//       we can just bind the build.zig.zon as a module directly to allow importing
const build_zon: struct {
    name: @Type(.enum_literal),
    version: []const u8,
    fingerprint: u64,
    minimum_zig_version: []const u8,
    dependencies: struct {
        raylib_zig: struct {
            url: []const u8,
            hash: []const u8,
        },
        clap: struct {
            url: []const u8,
            hash: []const u8,
        },
        fontconfig: struct {
            path: []const u8,
            lazy: bool,
            // url: []const u8,
            // hash: []const u8,
        },
        zg: struct {
            url: []const u8,
            hash: []const u8,
        },
    },
    paths: []const []const u8,
} = @import("build.zig.zon");
const SOURCE_DIR = "src/";
const META_FILE = SOURCE_DIR ++ "meta.zig";

const TARGETS = [_]std.Target.Query {
    // .{ .os_tag = .linux, .cpu_arch = .arm, },
    // .{ .os_tag = .linux, .cpu_arch = .x86_64, },
    // .{ .os_tag = .linux, .cpu_arch = .x86, },

    // .{ .os_tag = .macos, .cpu_arch = .arm, },
    // .{ .os_tag = .macos, .cpu_arch = .x86_64, },

    // .{ .os_tag = .windows, .cpu_arch = .arm, },
    // .{ .os_tag = .windows, .cpu_arch = .x86_64, },
};

// For dynamic linking, we prefer dynamic linking and to search by
// mode first. Mode first will search all paths for a dynamic library
// before falling back to static.
const dynamic_link_opts: std.Build.Module.LinkSystemLibraryOptions = .{
    .preferred_link_mode = .dynamic,
    .search_strategy = .mode_first,
};

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // const build_zon = b.createModule(.{
    //     .root_source_file = b.path("build.zig.zon"),
    //     .target = target,
    //     .optimize = optimize,
    // });
    // exe.root_module.addImport("microwave", microwave.module("microwave"));
    const host_exe_mod = b.createModule(.{
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
    });
    const host_exe = create_exe(
        b,
        host_exe_mod,
        target,
        optimize,
        // build_zon,
    );
    host_exe.step.dependOn(writeMetaFileStep(b));
    b.installArtifact(host_exe);

    // for (TARGETS) |target_query| {
    //     const resolved_target= b.resolveTargetQuery(target_query);
    //     const exe_mod = b.createModule(.{
    //         .root_source_file = b.path("src/main.zig"),
    //         .target = resolved_target,
    //         .optimize = optimize,
    //     });
    //     const exe = create_exe(
    //         b,
    //         exe_mod,
    //         resolved_target,
    //         optimize,
    //         // build_zon,
    //     );
    //     b.installArtifact(exe);
    // }

    const run_cmd = b.addRunArtifact(host_exe);
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| {
        run_cmd.addArgs(args);
    }

    const run_step = b.step("run", "Run the app");
    run_step.dependOn(&run_cmd.step);

    const exe_unit_tests = b.addTest(.{
        .root_module = host_exe_mod,
    });
    const run_exe_unit_tests = b.addRunArtifact(exe_unit_tests);

    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&run_exe_unit_tests.step);
}

fn writeMetaFileStep(b: *std.Build) *std.Build.Step {
    const write_version_step = b.addUpdateSourceFiles();
    var now: ctime.time_t = undefined;
    _ = ctime.time(&now);
    const timeinfo: [*c]ctime.struct_tm = ctime.localtime(&now);
    const s: [*c]const u8 = ctime.asctime(timeinfo);
    const file_data: []u8 = b.fmt(
        "// WARN: Autogenerated at build time, do NOT modify manually \n"
        ++ "pub const NAME: []const u8 = \"" ++ @tagName(build_zon.name) ++ "\";\n"
        ++ "pub const VERSION: []const u8 = \"" ++ build_zon.version ++ "\";\n"
        ++ "pub const COMPILATION_DATE: []const u8 = \"{s}\";",
        .{s[0..std.mem.len(s) - 1]},
    );
    write_version_step.addBytesToSource(
        file_data,
        META_FILE,
    );
    return &write_version_step.step;
}

fn create_exe(
    b: *std.Build,
    module: *std.Build.Module,
    target: std.Build.ResolvedTarget,
    optimize: std.builtin.OptimizeMode,
    // build_zon: *std.Build.Module,
) *std.Build.Step.Compile {
    // These dependencies we want to default false if we're on macOS.
    // On macOS we don't want to use system libraries because we
    // generally want a fat binary. This can be overridden with the
    // `-fsys` flag.
    for (&[_][]const u8{
        "fontconfig",
        "libpng",
        "zlib",
    }) |dep| {
        _ = b.systemIntegrationOption(
            dep,
            .{
                // If we're not on darwin we want to use whatever the
                // default is via the system package mode
                .default = if (target.result.os.tag.isDarwin()) false else null,
            },
        );
    }

    const raylib = b.dependency("raylib_zig", .{
        .target = target,
        .optimize = optimize,
        // .linux_display_backend = .X11
    });
    const clap = b.dependency("clap", .{
        .target = target,
        .optimize = optimize,
    });
    _ = b.systemIntegrationOption("fontconfig", .{}); // Shows it in help
    const fontconfig = b.lazyDependency("fontconfig", .{
        .target = target,
        .optimize = optimize,
    }) orelse @panic("Missing fontconfig");

    const zg = b.dependency("zg", .{
        .target = target,
        .optimize = optimize,
    });
    const exe = b.addExecutable(.{
        .name = "de_menu",
        .root_module = module,
    });
    exe.linkLibrary(raylib.artifact("raylib"));
    // NOTE: This GitHub issue is useful for figuring
    //       out how to link stuff: https://github.com/ziglang/zig/issues/11151
    // TODO: Remove this once libxml2 support is fixed
    // exe.linkSystemLibrary("expat");
    // exe.linkLibrary(fontconfig.artifact("fontconfig"));
    exe.root_module.addImport(
        "fontconfig",
        fontconfig.module("fontconfig"),
    );
    if (b.systemIntegrationOption("fontconfig", .{})) {
        exe.linkSystemLibrary2("fontconfig", dynamic_link_opts);
    } else {
        exe.linkLibrary(fontconfig.artifact("fontconfig"));
        _ = fontconfig.artifact("fontconfig").getEmittedBin();
    }
    // exe.root_module.addImport("build_zon", build_zon);
    exe.root_module.addImport("raylib", raylib.module("raylib"));
    exe.root_module.addImport("raygui", raylib.module("raygui"));
    exe.root_module.addImport("clap", clap.module("clap"));
    exe.root_module.addImport("zg_case_folding", zg.module("CaseFolding"));
    exe.root_module.addImport("zg_letter_casing", zg.module("LetterCasing"));
    return exe;
}
