// WARN: Autogenerated at build time, do NOT modify manually 
pub const NAME: []const u8 = "de_menu";
pub const VERSION: []const u8 = "0.1.0";
pub const COMPILATION_DATE: []const u8 = "Wed Jun  4 20:42:10 2025";