// WARN: Autogenerated at build time, do NOT modify manually 
pub const NAME: []const u8 = "de_menu";
pub const VERSION: []const u8 = "0.2.0";
pub const COMPILATION_DATE: []const u8 = "2025-06-26T08:05:06.849Z";